version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 50
    ignore:
      - dependency-name: "microbundle-crl"
      - dependency-name: "babel-eslint"
      - dependency-name: "eslint*"
      - dependency-name: "@storybook/*"
