name: Tests
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  tests:
    strategy:
      matrix:
        node-version: [20.x]
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Install Dependencies
        run: pnpm ci
      - name: Lint Checks
        run: pnpm run test:lint
      - name: Typescript Checks
        run: pnpm run type-check
      - name: Unit Tests
        run: pnpm run test:unit
        env:
          CI: true
      - name: End to End Tests (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo DEBIAN_FRONTEND=noninteractive apt-get install -y xvfb && xvfb-run pnpm run test:playwright:headed
        env:
          CI: true
      - name: End to End Tests (Windows & MacOS)
        if: runner.os != 'Linux'
        run: pnpm run test:playwright
        env:
          CI: true
      - name: Upload Playwright Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report-${{ github.sha }}-${{matrix.os}}-${{ matrix.node-version }}
          path: playwright-report
      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        if: matrix.os == 'ubuntu-latest'
        with:
          name: coverage-report-${{ github.sha }}-${{ matrix.node-version }}
          path: coverage
