name: Tests
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  tests:
    strategy:
      matrix:
        node-version: [20.x]
        os: [ubuntu-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Run tests
        run: pnpm run test:docker
      - name: Modify coverage report
        run: |
          # Replace /usr/src/react-ui/ with the current working directory in all coverage reports files
          sudo chmod -R 777 test-artifacts/coverage
          for file in test-artifacts/coverage/coverage-summary.json test-artifacts/coverage/coverage-final.json; do
            sed -i "s#/usr/src/react-ui#$(pwd)#g" "$file"
          done
      - name: "Report coverage"
        uses: davelosert/vitest-coverage-report-action@v2
        if: always()
        with:
          file-coverage-mode: all
          json-summary-path: test-artifacts/coverage/coverage-summary.json
          json-final-path: test-artifacts/coverage/coverage-final.json
